;;; This file was automatically generated by SWIG (http://www.swig.org).
;;; Version 3.0.12
;;;
;;; Do not make changes to this file unless you know what you are doing--modify
;;; the SWIG interface file instead.

(in-package :lcm)
;;;SWIG wrapper code starts here

(cl:defmacro defanonenum (cl:&body enums)
   "Converts anonymous enums to defconstants."
  `(cl:progn ,@(cl:loop for value in enums
                        for index = 0 then (cl:1+ index)
                        when (cl:listp value) do (cl:setf index (cl:second value)
                                                          value (cl:first value))
                        collect `(cl:defconstant ,value ,index))))

(cl:eval-when (:compile-toplevel :load-toplevel)
  (cl:unless (cl:fboundp 'swig-lispify)
    (cl:defun swig-lispify (name flag cl:&optional (package cl:*package*))
      (cl:labels ((helper (lst last rest cl:&aux (c (cl:car lst)))
                    (cl:cond
                      ((cl:null lst)
                       rest)
                      ((cl:upper-case-p c)
                       (helper (cl:cdr lst) 'upper
                               (cl:case last
                                 ((lower digit) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:lower-case-p c)
                       (helper (cl:cdr lst) 'lower (cl:cons (cl:char-upcase c) rest)))
                      ((cl:digit-char-p c)
                       (helper (cl:cdr lst) 'digit 
                               (cl:case last
                                 ((upper lower) (cl:list* c #\- rest))
                                 (cl:t (cl:cons c rest)))))
                      ((cl:char-equal c #\_)
                       (helper (cl:cdr lst) '_ (cl:cons #\- rest)))
                      (cl:t
                       (cl:error "Invalid character: ~A" c)))))
        (cl:let ((fix (cl:case flag
                        ((constant enumvalue) "+")
                        (variable "*")
                        (cl:t ""))))
          (cl:intern
           (cl:concatenate
            'cl:string
            fix
            (cl:nreverse (helper (cl:concatenate 'cl:list name) cl:nil cl:nil))
            fix)
           package))))))

;;;SWIG wrapper code ends here


(cl:defconstant LCM_MAX_MESSAGE_SIZE (cl:ash 1 28))

(cl:defconstant LCM_MAX_CHANNEL_NAME_LENGTH 63)

(cffi:defcstruct _lcm_recv_buf_t
	(data :pointer)
	(data_size :uint32)
	(recv_utime :int64)
	(lcm :pointer))

(cffi:defcfun ("lcm_create" lcm_create) :pointer
  (provider :string))

(cffi:defcfun ("lcm_destroy" lcm_destroy) :void
  (lcm :pointer))

(cffi:defcfun ("lcm_get_fileno" lcm_get_fileno) :int
  (lcm :pointer))

(cffi:defcfun ("lcm_subscribe" lcm_subscribe) :pointer
  (lcm :pointer)
  (channel :string)
  (handler :pointer)
  (userdata :pointer))

(cffi:defcfun ("lcm_unsubscribe" lcm_unsubscribe) :int
  (lcm :pointer)
  (handler :pointer))

(cffi:defcfun ("lcm_publish" lcm_publish) :int
  (lcm :pointer)
  (channel :string)
  (data :pointer)
  (datalen :unsigned-int))

(cffi:defcfun ("lcm_handle" lcm_handle) :int
  (lcm :pointer))

(cffi:defcfun ("lcm_handle_timeout" lcm_handle_timeout) :int
  (lcm :pointer)
  (timeout_millis :int))

(cffi:defcfun ("lcm_subscription_set_queue_capacity" lcm_subscription_set_queue_capacity) :int
  (handler :pointer)
  (num_messages :int))

(cl:defconstant LCM_MAJOR_VERSION 1)

(cl:defconstant LCM_MINOR_VERSION 3)

(cl:defconstant LCM_MICRO_VERSION 1)


